name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.5.1
  flutter_vector_icons: ^2.0.0
  dio: ^5.4.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true